version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  news_digest_mcp_bot:
    build: .
    volumes:
      - .:/app
    container_name: news_digest_mcp_bot
    ports:
      - "8000:8000"
    environment:
      - THENEWS_API_KEY=${THENEWS_API_KEY}
      - HF_API_TOKEN=${HF_API_TOKEN}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant

volumes:
  qdrant_data:
