name: CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      THENEWS_API_KEY: ${{ secrets.THENEWS_API_KEY }}
      HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      PINECONE_ENV: ${{ secrets.PINECONE_ENV }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install --no-root --no-interaction --no-ansi

    # - name: Run tests
    #   run: poetry run pytest tests/
